apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-phpfpm
  name: nginx-phpfpm
spec:
  volumes:
  - name: shared-files
    emptyDir: {}
  - name: nginx-config-volume
    configMap:
        name: nginx-config
  containers:
  - image: nginx:latest
    name: nginx-container
    resources: {}
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx.conf
      subPath: nginx.conf
  - image: php:7.2-fpm
    name: php-fpm-container
    volumeMounts:
    - name: shared-files
      mountPath: /var/www/html   
  dnsPolicy: ClusterFirst
  restartPolicy: Always
